services:
  - type: web
    name: mini-blog
    env: python
    buildCommand: cd blog && pip install -r requirements.txt
    startCommand: cd blog && gunicorn blog.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: blog.settings
      - key: DATABASE_URL
        fromDatabase:
          name: mini_blog_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 
